spring.application.name=gerenciador-de-tarefas-spring
spring.datasource.url=jdbc:mysql://localhost:3307/tarefas
spring.datasource.username=salomao
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update